### ISSUE TITLE
License

### ISSUE THREAD

**Issue by lloydarnold** [artem-oppermann/Sentiment-Analysis-of-Netflix-Reviews#4]
Hi @artem-oppermann -- I'm a computer science student and I'm trying to learn about natural language processing at the moment. I've found reading your code really useful, and have used a couple of your subroutines in my own project -- I'm planning on writing my own as soon as I really understand what's going on, but wanted a way in. However, I've noticed that you haven't included any license in your project, which means normal copywrite laws apply -- is it okay for me to use your code in this manner? I have cited it as yours clearly throughout my project. 

Thanks.

**Comment by artem-oppermann** [comment]
Hi @lloydarnold . Yes feel free to use the code.

**Comment by lloydarnold** [comment]
Thankyou !
